---
title: "lab07_assignment"
author: "Group17"
format: html
editor: visual
---

## Importing libraries

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(cowplot)
library(here)
```

## Load data

```{r message=FALSE, warning=FALSE}
#|echo: false
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Look at the data

The explained variable is going to be the outcome column ie. weather or not a tumor is benign or malignant, so we place this col first

```{r}
biopsy <- biopsy |> select(outcome,everything())
biopsy
```

## Creating the PCA model

We are now going to project the dataset into a plane of the 2 most significant dimensions (linear combinations of the variables)

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |>
  prcomp(scale = TRUE)

```

## Plotting the PCA

```{r}
pca_fit |>
  augment(biopsy) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "red", benign = "blue")
  )
```

## Rotation matrix
